#!/usr/bin/env python3
"""Install the git-hook wrappers into ``.git/hooks/`` (FR-001).

Writes one thin bash wrapper per event that `exec`s the matching Python entry
point with the *current* interpreter — the one that has aspis (and PyYAML)
installed — so the hooks resolve their dependencies the same way the engine does.
Idempotent: re-running rewrites identical wrappers.
"""

from __future__ import annotations

import stat
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent))

import _git  # noqa: E402

# git hook name -> entry-point module in this directory.
_HOOKS = {
    "pre-commit": "precommit.py",
    "commit-msg": "commitmsg.py",
    "post-commit": "postcommit.py",
}
_WRAPPER = (
    "#!/usr/bin/env bash\n"
    "# Managed by ASPIS — regenerated by install.py.\n"
    'exec "{python}" "{entry}" "$@"\n'
)


def install(root: Path) -> list[str]:
    """Write the wrappers; return the hook names written (empty if no .git)."""
    hooks_dir = root / ".git" / "hooks"
    if not (root / ".git").exists():
        return []
    hooks_dir.mkdir(parents=True, exist_ok=True)
    here = Path(__file__).resolve().parent
    written: list[str] = []
    for hook, entry in _HOOKS.items():
        target = hooks_dir / hook
        target.write_text(
            _WRAPPER.format(python=sys.executable, entry=here / entry),
            encoding="utf-8",
            newline="\n",
        )
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        written.append(hook)
    return written


def main(argv: list[str] | None = None) -> int:
    """`python install.py [root]` — arm the git hooks."""
    args = argv if argv is not None else sys.argv[1:]
    root = Path(args[0]).resolve() if args else _git.repo_root()
    written = install(root)
    print(f"[aspis] installed git hooks: {', '.join(written) or 'none (no .git)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
