"""Project-layer helpers: identifying an ASPIS project and reading its settings.

A directory is an ASPIS project when it contains the brain folder (``.aspis/``) —
the durable, tool-neutral memory for that project. Project-tunable settings live in
``.aspis/config/project.yaml`` (the default build mode, model overrides); machine
state lives in the manifest. Keeping both in one place means every command agrees
on what "a project" means and where its settings are.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from aspis import paths
from aspis.constants import BRAIN_DIR

#: The build modes a project may default to (matches config/modes.yaml).
VALID_MODES = ("vibe", "mvp", "production")

#: Project-relative path to the human-editable settings file.
PROJECT_CONFIG_REL = Path(BRAIN_DIR) / "config" / "project.yaml"


def is_project(root: Path) -> bool:
    """Return True if ``root`` contains an ASPIS brain folder."""
    return (root / BRAIN_DIR).is_dir()


def config_path(root: Path) -> Path:
    """Return the path to the project's settings file."""
    return root / PROJECT_CONFIG_REL


def load_project_config(root: Path) -> dict:
    """Return the parsed project settings, or ``{}`` when none exist."""
    path = config_path(root)
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def global_config_path() -> Path:
    """Path to the machine-wide ASPIS settings file (``project.yaml``).

    The directory is the OS-standard config home (see :mod:`aspis.paths`):
    ``ASPIS_HOME`` overrides it, an existing legacy ``~/.aspis`` is honoured, else
    ``~/.config/aspis`` / ``%APPDATA%\\ASPIS``. This layer sits below project config
    in model resolution.
    """
    return paths.config_home() / "project.yaml"


def load_global_config() -> dict:
    """Return the machine-wide ASPIS settings, or ``{}`` when none exist."""
    path = global_config_path()
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


#: The generated, user-editable per-agent model assignment file.
AGENT_MODELS_REL = Path(BRAIN_DIR) / "config" / "agent-models.yaml"

#: Routing keys ``agent-models.yaml`` owns (it is authoritative for these over project.yaml).
_ROUTING_KEYS = ("runtimes", "agents", "models")


def load_agent_models(root: Path) -> dict:
    """Return the parsed ``agent-models.yaml`` (per-agent model assignments), or ``{}``."""
    path = root / AGENT_MODELS_REL
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def load_effective_config(root: Path) -> dict:
    """Project config with ``agent-models.yaml`` overlaid as the authoritative routing source.

    ``project.yaml`` keeps ``mode`` and anything else; the dedicated ``agent-models.yaml``
    (generated by ``aspis models --sync``, then hand-edited) is where per-agent model choices
    live, so it wins for the routing keys. Used by export/render and ``aspis models``.
    """
    config = load_project_config(root)
    agent_models = load_agent_models(root)
    for key in _ROUTING_KEYS:
        if key in agent_models:
            config[key] = agent_models[key]
    return config


def default_mode(root: Path, *, fallback: str = "production") -> str:
    """Return the project's default build mode, falling back when unset."""
    mode = load_project_config(root).get("mode")
    return mode if mode in VALID_MODES else fallback


def set_mode(root: Path, mode: str) -> None:
    """Set the project's default build mode, preserving the file's other content.

    Replaces the ``mode:`` line in place (keeping comments) when present, else
    creates the file with a single ``mode:`` key.
    """
    if mode not in VALID_MODES:
        raise ValueError(f"unknown mode {mode!r}; expected one of {VALID_MODES}")
    path = config_path(root)
    if path.is_file():
        lines = path.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            if line.strip().startswith("mode:") and not line.lstrip().startswith("#"):
                lines[i] = f"mode: {mode}"
                break
        else:
            lines.insert(0, f"mode: {mode}")
        text = "\n".join(lines) + "\n"
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        text = f"mode: {mode}\n"
    path.write_text(text, encoding="utf-8", newline="\n")
